---
title: "Manuscript Test" 
author: "Ian Parfitt" 
date: "'r Sys.Date()'"
geometry: margin=1in
header-includes:
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{lineno}
  - \linenumbers
  - \usepackage{fontspec}       #can only be used with xelatex output
  - \setmainfont{Times New Roman} # can only be used with xelatex output

output: 
  pdf_document: 
    latex_engine: xelatex 
# Other output options are: 
# output: html_document
# output: word_document

## Specify your csl here. You can use local or remote (local is better?)
## Sources of csl files:
## <https://github.com/citation-style-language/styles-distribution>
## or is it <https://github.com/citation-style-language/styles>
## <https://www.zotero.org/styles>
## <https://github.com/citation-style-language/styles/blob/master/ecology-letters.csl>
## or is it <https://githubusercontent.com/citation-style-language/styles/master/ecology-letters.csl>

csl: <https://www.zotero.org/styles/ecology-letters>
bibliography: prod_repro.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(palmerpenguins)
library(GGally)
library(kableExtra)
```

Title: The Title of this paper

First Author^1^; Second Author^2\*^

1.  Dept of
2.  Environmental Institute

\*Corresponding Author

\newpage

# Abstract

# Introduction

Some fake text [@guidoni-martins2021]

# Methods

$$
H_x = -S[P(1_x) \times ln(P(1_x))]
$$

# Results

# Discussion

# References

::: {#refs}
:::

# Tables

Table 1. Caption

```{r table_01, echo=FALSE, message=FALSE, warning=FALSE}

penguin_sum <- penguins %>%
  group_by(island, year) %>%
  summarize(mean_body_mass_g = mean(body_mass_g, na.rm = TRUE)) %>%
  ungroup()

kable(x=penguin_sum,
      col.names = c("Island", "Year", "Mean Body Mass (g)")) %>%
  kable_styling(latex_options = "hold_position")
# without the the held_position the table ends up at the top of the page
```

# Figure Captions

# Figures

```{r file = "..."}
# this code chunk calls an external script

```

# Appendices
